pandas- pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. it provides two primary data structure.

# pandas 1-d

In [1]:
import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

data2=pd.array([10,20,30,40,50])
print(data2)

data3=pd.array([10,20,30,40,50])
print(data3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<IntegerArray>
[10, 20, 30, 40, 50]
Length: 5, dtype: Int64
<IntegerArray>
[10, 20, 30, 40, 50]
Length: 5, dtype: Int64

pandas 1-d dictinory...

In [2]:

data={'a':1,'b':2,'c':3}
series=pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [3]:
# create a dataframe from a dictionary of list
data={
    'name':['Alice','Bob','Charlie'],
    'age':[25,30,35],
    'city':['New York','Los Angeles','Chicago']
}
df=pd.DataFrame(data)
print(df)
print('--'*20)
#data_new=[
#    {'name':'Alice','age':25,'city':'New York'},
#    {'name':'Bob','age':30,'city':'Los Angeles'},
#    {'name':'Charlie','age':35,'city':'Chicago'}
#]
#df1=pd.DataFrame(data_new)
#print(df1)

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
----------------------------------------

# manipulating data with dataframe

In [4]:
# add a new column to the dataframe
df['salary']=[50000,60000,70000]
df

      name  age         city  salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [5]:
# delete a column from the dataframe
df.drop('salary',axis=1,inplace=True)

# add +1 in age

In [6]:
df['age']=df['age']+1
df

      name  age         city
0    Alice   26     New York
1      Bob   31  Los Angeles
2  Charlie   36      Chicago